"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class imp_gains_cmd_t(object):

    __slots__ = ["timestamp", "kq_scale", "dq_scale", "kt_trans_scale", "kt_rot_scale", "dt_trans_scale", "dt_rot_scale", "mode"]

    __typenames__ = ["double", "float", "float", "float", "float", "float", "float", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.kq_scale = 0.0
        """ LCM Type: float """
        self.dq_scale = 0.0
        """ LCM Type: float """
        self.kt_trans_scale = 0.0
        """ LCM Type: float """
        self.kt_rot_scale = 0.0
        """ LCM Type: float """
        self.dt_trans_scale = 0.0
        """ LCM Type: float """
        self.dt_rot_scale = 0.0
        """ LCM Type: float """
        self.mode = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(imp_gains_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dffffffb", self.timestamp, self.kq_scale, self.dq_scale, self.kt_trans_scale, self.kt_rot_scale, self.dt_trans_scale, self.dt_rot_scale, self.mode))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imp_gains_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imp_gains_cmd_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = imp_gains_cmd_t()
        self.timestamp, self.kq_scale, self.dq_scale, self.kt_trans_scale, self.kt_rot_scale, self.dt_trans_scale, self.dt_rot_scale, self.mode = struct.unpack(">dffffffb", buf.read(33))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if imp_gains_cmd_t in parents: return 0
        tmphash = (0xc037d56d547f361c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if imp_gains_cmd_t._packed_fingerprint is None:
            imp_gains_cmd_t._packed_fingerprint = struct.pack(">Q", imp_gains_cmd_t._get_hash_recursive([]))
        return imp_gains_cmd_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", imp_gains_cmd_t._get_packed_fingerprint())[0]

