"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class imp_status_t(object):

    __slots__ = ["timestamp", "mode", "num_joints", "num_arm", "q", "q_nom", "p", "p_nom", "quat_wxyz", "quat_nom_wxyz", "xi", "kq_scale", "dq_scale", "kt_trans", "kt_rot", "dt_trans", "dt_rot"]

    __typenames__ = ["double", "int8_t", "int32_t", "int32_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, ["num_joints"], ["num_joints"], [3], [3], [4], [4], [6], None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.mode = 0
        """ LCM Type: int8_t """
        self.num_joints = 0
        """
        0=joint, 1=task
        LCM Type: int32_t
        """

        self.num_arm = 0
        """ LCM Type: int32_t """
        self.q = []
        """ LCM Type: float[num_joints] """
        self.q_nom = []
        """ LCM Type: float[num_joints] """
        self.p = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.p_nom = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.quat_wxyz = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.quat_nom_wxyz = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.xi = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.kq_scale = 0.0
        """
        SE3 body error (v, w) pinocchio order when task; joint: zeros except first dims unused
        LCM Type: float
        """

        self.dq_scale = 0.0
        """ LCM Type: float """
        self.kt_trans = 0.0
        """ LCM Type: float """
        self.kt_rot = 0.0
        """ LCM Type: float """
        self.dt_trans = 0.0
        """ LCM Type: float """
        self.dt_rot = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(imp_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dbii", self.timestamp, self.mode, self.num_joints, self.num_arm))
        buf.write(struct.pack('>%df' % self.num_joints, *self.q[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.q_nom[:self.num_joints]))
        buf.write(struct.pack('>3f', *self.p[:3]))
        buf.write(struct.pack('>3f', *self.p_nom[:3]))
        buf.write(struct.pack('>4f', *self.quat_wxyz[:4]))
        buf.write(struct.pack('>4f', *self.quat_nom_wxyz[:4]))
        buf.write(struct.pack('>6f', *self.xi[:6]))
        buf.write(struct.pack(">ffffff", self.kq_scale, self.dq_scale, self.kt_trans, self.kt_rot, self.dt_trans, self.dt_rot))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imp_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imp_status_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = imp_status_t()
        self.timestamp, self.mode, self.num_joints, self.num_arm = struct.unpack(">dbii", buf.read(17))
        self.q = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.q_nom = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.p = struct.unpack('>3f', buf.read(12))
        self.p_nom = struct.unpack('>3f', buf.read(12))
        self.quat_wxyz = struct.unpack('>4f', buf.read(16))
        self.quat_nom_wxyz = struct.unpack('>4f', buf.read(16))
        self.xi = struct.unpack('>6f', buf.read(24))
        self.kq_scale, self.dq_scale, self.kt_trans, self.kt_rot, self.dt_trans, self.dt_rot = struct.unpack(">ffffff", buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if imp_status_t in parents: return 0
        tmphash = (0xd35e2f710e0cda69) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if imp_status_t._packed_fingerprint is None:
            imp_status_t._packed_fingerprint = struct.pack(">Q", imp_status_t._get_hash_recursive([]))
        return imp_status_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", imp_status_t._get_packed_fingerprint())[0]

