"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class p2p_gains_cmd_t(object):

    __slots__ = ["timestamp", "kp_scale", "kd_scale", "fjc_scale", "friction_phi", "do_friction_comp"]

    __typenames__ = ["double", "float", "float", "float", "float", "boolean"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.kp_scale = 0.0
        """ LCM Type: float """
        self.kd_scale = 0.0
        """ LCM Type: float """
        self.fjc_scale = 0.0
        """ LCM Type: float """
        self.friction_phi = 0.0
        """ LCM Type: float """
        self.do_friction_comp = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(p2p_gains_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dffffb", self.timestamp, self.kp_scale, self.kd_scale, self.fjc_scale, self.friction_phi, self.do_friction_comp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != p2p_gains_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return p2p_gains_cmd_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = p2p_gains_cmd_t()
        self.timestamp, self.kp_scale, self.kd_scale, self.fjc_scale, self.friction_phi = struct.unpack(">dffff", buf.read(24))
        self.do_friction_comp = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if p2p_gains_cmd_t in parents: return 0
        tmphash = (0x68915096c9096c2e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if p2p_gains_cmd_t._packed_fingerprint is None:
            p2p_gains_cmd_t._packed_fingerprint = struct.pack(">Q", p2p_gains_cmd_t._get_hash_recursive([]))
        return p2p_gains_cmd_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", p2p_gains_cmd_t._get_packed_fingerprint())[0]

