"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class p2p_status_t(object):

    __slots__ = ["timestamp", "mode", "num_joints", "num_arm", "q", "q_des", "qd", "qd_des", "kp", "kd", "fjc", "friction_phi", "kp_scale", "kd_scale", "fjc_scale", "do_friction_comp", "do_grav_comp"]

    __typenames__ = ["double", "int8_t", "int32_t", "int32_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "boolean", "boolean"]

    __dimensions__ = [None, None, None, None, ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.mode = 0
        """ LCM Type: int8_t """
        self.num_joints = 0
        """
        0=hold, 1=track, 2=grav
        LCM Type: int32_t
        """

        self.num_arm = 0
        """ LCM Type: int32_t """
        self.q = []
        """ LCM Type: float[num_joints] """
        self.q_des = []
        """ LCM Type: float[num_joints] """
        self.qd = []
        """ LCM Type: float[num_joints] """
        self.qd_des = []
        """ LCM Type: float[num_joints] """
        self.kp = []
        """ LCM Type: float[num_joints] """
        self.kd = []
        """ LCM Type: float[num_joints] """
        self.fjc = []
        """ LCM Type: float[num_joints] """
        self.friction_phi = 0.0
        """ LCM Type: float """
        self.kp_scale = 0.0
        """ LCM Type: float """
        self.kd_scale = 0.0
        """ LCM Type: float """
        self.fjc_scale = 0.0
        """ LCM Type: float """
        self.do_friction_comp = False
        """ LCM Type: boolean """
        self.do_grav_comp = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(p2p_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dbii", self.timestamp, self.mode, self.num_joints, self.num_arm))
        buf.write(struct.pack('>%df' % self.num_joints, *self.q[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.q_des[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.qd[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.qd_des[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.kp[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.kd[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.fjc[:self.num_joints]))
        buf.write(struct.pack(">ffffbb", self.friction_phi, self.kp_scale, self.kd_scale, self.fjc_scale, self.do_friction_comp, self.do_grav_comp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != p2p_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return p2p_status_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = p2p_status_t()
        self.timestamp, self.mode, self.num_joints, self.num_arm = struct.unpack(">dbii", buf.read(17))
        self.q = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.q_des = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.qd = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.qd_des = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.kp = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.kd = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.fjc = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.friction_phi, self.kp_scale, self.kd_scale, self.fjc_scale = struct.unpack(">ffff", buf.read(16))
        self.do_friction_comp = bool(struct.unpack('b', buf.read(1))[0])
        self.do_grav_comp = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if p2p_status_t in parents: return 0
        tmphash = (0x644aea7120e0f686) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if p2p_status_t._packed_fingerprint is None:
            p2p_status_t._packed_fingerprint = struct.pack(">Q", p2p_status_t._get_hash_recursive([]))
        return p2p_status_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", p2p_status_t._get_packed_fingerprint())[0]

