
name: click_and_point
# visualization_for_debug: True

# continuous mode would continously publishing the previous clicked point
# Note, the point would not be updated. 
continous_mode: True

sub_manager:
  name: single_rgbd
  rgbd_channel: d455_1
  # rgbd_channel: upper_camera
  max_sub_freq: 2000
pub_manager:
  # name: point3d
  # point_channel: click_and_point
  name: named_vec
  named_vec_list_channel: click_and_point

  max_pub_freq: 2000