"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class col_info_t(object):

    __slots__ = ["timestamp", "num_col_geoms", "len_concat_sizes", "concat_names", "concat_geom_types", "list_size_dims", "concat_sizes", "list_offsets"]

    __typenames__ = ["float", "int32_t", "int32_t", "string", "string", "int32_t", "float", "float"]

    __dimensions__ = [None, None, None, None, None, ["num_col_geoms"], ["len_concat_sizes"], ["num_col_geoms", 4, 4]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: float """
        self.num_col_geoms = 0
        """ LCM Type: int32_t """
        self.len_concat_sizes = 0
        """ LCM Type: int32_t """
        self.concat_names = ""
        """ LCM Type: string """
        self.concat_geom_types = ""
        """ LCM Type: string """
        self.list_size_dims = []
        """ LCM Type: int32_t[num_col_geoms] """
        self.concat_sizes = []
        """ LCM Type: float[len_concat_sizes] """
        self.list_offsets = []
        """ LCM Type: float[num_col_geoms][4][4] """

    def encode(self):
        buf = BytesIO()
        buf.write(col_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fii", self.timestamp, self.num_col_geoms, self.len_concat_sizes))
        __concat_names_encoded = self.concat_names.encode('utf-8')
        buf.write(struct.pack('>I', len(__concat_names_encoded)+1))
        buf.write(__concat_names_encoded)
        buf.write(b"\0")
        __concat_geom_types_encoded = self.concat_geom_types.encode('utf-8')
        buf.write(struct.pack('>I', len(__concat_geom_types_encoded)+1))
        buf.write(__concat_geom_types_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>%di' % self.num_col_geoms, *self.list_size_dims[:self.num_col_geoms]))
        buf.write(struct.pack('>%df' % self.len_concat_sizes, *self.concat_sizes[:self.len_concat_sizes]))
        for i0 in range(self.num_col_geoms):
            for i1 in range(4):
                buf.write(struct.pack('>4f', *self.list_offsets[i0][i1][:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != col_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return col_info_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = col_info_t()
        self.timestamp, self.num_col_geoms, self.len_concat_sizes = struct.unpack(">fii", buf.read(12))
        __concat_names_len = struct.unpack('>I', buf.read(4))[0]
        self.concat_names = buf.read(__concat_names_len)[:-1].decode('utf-8', 'replace')
        __concat_geom_types_len = struct.unpack('>I', buf.read(4))[0]
        self.concat_geom_types = buf.read(__concat_geom_types_len)[:-1].decode('utf-8', 'replace')
        self.list_size_dims = struct.unpack('>%di' % self.num_col_geoms, buf.read(self.num_col_geoms * 4))
        self.concat_sizes = struct.unpack('>%df' % self.len_concat_sizes, buf.read(self.len_concat_sizes * 4))
        self.list_offsets = []
        for i0 in range(self.num_col_geoms):
            self.list_offsets.append([])
            for i1 in range(4):
                self.list_offsets[i0].append(struct.unpack('>4f', buf.read(16)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if col_info_t in parents: return 0
        tmphash = (0x34820d6c712e9263) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if col_info_t._packed_fingerprint is None:
            col_info_t._packed_fingerprint = struct.pack(">Q", col_info_t._get_hash_recursive([]))
        return col_info_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", col_info_t._get_packed_fingerprint())[0]

