"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct


class point_3d_traj_t(object):

    __slots__ = [
        "timestamp",
        "num_times",
        "t_discrete",
        "point_3d_traj_des",
        "v_traj_des",
    ]

    __typenames__ = ["float", "int32_t", "float", "float", "float"]

    __dimensions__ = [None, None, ["num_times"], ["num_times", 3], ["num_times", 3]]

    def __init__(self):
        self.timestamp = 0.0
        """
        Points Traj. in R^3
        LCM Type: float
        """

        self.num_times = 0
        """ LCM Type: int32_t """
        self.t_discrete = []
        """ LCM Type: float[num_times] """
        self.point_3d_traj_des = []
        """ LCM Type: float[num_times][3] """
        self.v_traj_des = []
        """ LCM Type: float[num_times][3] """

    def encode(self):
        buf = BytesIO()
        buf.write(point_3d_traj_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fi", self.timestamp, self.num_times))
        buf.write(
            struct.pack(">%df" % self.num_times, *self.t_discrete[: self.num_times])
        )
        for i0 in range(self.num_times):
            buf.write(struct.pack(">3f", *self.point_3d_traj_des[i0][:3]))
        for i0 in range(self.num_times):
            buf.write(struct.pack(">3f", *self.v_traj_des[i0][:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != point_3d_traj_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return point_3d_traj_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = point_3d_traj_t()
        self.timestamp, self.num_times = struct.unpack(">fi", buf.read(8))
        self.t_discrete = struct.unpack(
            ">%df" % self.num_times, buf.read(self.num_times * 4)
        )
        self.point_3d_traj_des = []
        for i0 in range(self.num_times):
            self.point_3d_traj_des.append(struct.unpack(">3f", buf.read(12)))
        self.v_traj_des = []
        for i0 in range(self.num_times):
            self.v_traj_des.append(struct.unpack(">3f", buf.read(12)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if point_3d_traj_t in parents:
            return 0
        tmphash = (0xEEC2C7E22997A96A) & 0xFFFFFFFFFFFFFFFF
        tmphash = (
            ((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)
        ) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if point_3d_traj_t._packed_fingerprint is None:
            point_3d_traj_t._packed_fingerprint = struct.pack(
                ">Q", point_3d_traj_t._get_hash_recursive([])
            )
        return point_3d_traj_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", point_3d_traj_t._get_packed_fingerprint())[0]
