"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class point_set_t(object):

    __slots__ = ["timestamp", "num_points", "position"]

    __typenames__ = ["float", "int32_t", "float"]

    __dimensions__ = [None, None, ["num_points", 3]]

    def __init__(self):
        self.timestamp = 0.0
        """
        Points in R^3
        LCM Type: float
        """

        self.num_points = 0
        """ LCM Type: int32_t """
        self.position = []
        """ LCM Type: float[num_points][3] """

    def encode(self):
        buf = BytesIO()
        buf.write(point_set_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fi", self.timestamp, self.num_points))
        for i0 in range(self.num_points):
            buf.write(struct.pack('>3f', *self.position[i0][:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != point_set_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return point_set_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = point_set_t()
        self.timestamp, self.num_points = struct.unpack(">fi", buf.read(8))
        self.position = []
        for i0 in range(self.num_points):
            self.position.append(struct.unpack('>3f', buf.read(12)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if point_set_t in parents: return 0
        tmphash = (0x4f43233a77e1f35a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if point_set_t._packed_fingerprint is None:
            point_set_t._packed_fingerprint = struct.pack(">Q", point_set_t._get_hash_recursive([]))
        return point_set_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", point_set_t._get_packed_fingerprint())[0]

