"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class point_3d_feature_t(object):

    __slots__ = ["timestamp", "num_points", "position", "num_feature_types", "concat_feature_names", "feature_dims", "concat_feature_dim", "concat_feature"]

    __typenames__ = ["float", "int32_t", "float", "int32_t", "string", "int32_t", "int32_t", "float"]

    __dimensions__ = [None, None, ["num_points", 3], None, None, ["num_feature_types"], None, ["num_points", "concat_feature_dim"]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: float """
        self.num_points = 0
        """ LCM Type: int32_t """
        self.position = []
        """ LCM Type: float[num_points][3] """
        self.num_feature_types = 0
        """ LCM Type: int32_t """
        self.concat_feature_names = ""
        """ LCM Type: string """
        self.feature_dims = []
        """
        parsed with ","
        LCM Type: int32_t[num_feature_types]
        """

        self.concat_feature_dim = 0
        """ LCM Type: int32_t """
        self.concat_feature = []
        """ LCM Type: float[num_points][concat_feature_dim] """

    def encode(self):
        buf = BytesIO()
        buf.write(point_3d_feature_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fi", self.timestamp, self.num_points))
        for i0 in range(self.num_points):
            buf.write(struct.pack('>3f', *self.position[i0][:3]))
        buf.write(struct.pack(">i", self.num_feature_types))
        __concat_feature_names_encoded = self.concat_feature_names.encode('utf-8')
        buf.write(struct.pack('>I', len(__concat_feature_names_encoded)+1))
        buf.write(__concat_feature_names_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>%di' % self.num_feature_types, *self.feature_dims[:self.num_feature_types]))
        buf.write(struct.pack(">i", self.concat_feature_dim))
        for i0 in range(self.num_points):
            buf.write(struct.pack('>%df' % self.concat_feature_dim, *self.concat_feature[i0][:self.concat_feature_dim]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != point_3d_feature_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return point_3d_feature_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = point_3d_feature_t()
        self.timestamp, self.num_points = struct.unpack(">fi", buf.read(8))
        self.position = []
        for i0 in range(self.num_points):
            self.position.append(struct.unpack('>3f', buf.read(12)))
        self.num_feature_types = struct.unpack(">i", buf.read(4))[0]
        __concat_feature_names_len = struct.unpack('>I', buf.read(4))[0]
        self.concat_feature_names = buf.read(__concat_feature_names_len)[:-1].decode('utf-8', 'replace')
        self.feature_dims = struct.unpack('>%di' % self.num_feature_types, buf.read(self.num_feature_types * 4))
        self.concat_feature_dim = struct.unpack(">i", buf.read(4))[0]
        self.concat_feature = []
        for i0 in range(self.num_points):
            self.concat_feature.append(struct.unpack('>%df' % self.concat_feature_dim, buf.read(self.concat_feature_dim * 4)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if point_3d_feature_t in parents: return 0
        tmphash = (0x82e30d28df5159d7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if point_3d_feature_t._packed_fingerprint is None:
            point_3d_feature_t._packed_fingerprint = struct.pack(">Q", point_3d_feature_t._get_hash_recursive([]))
        return point_3d_feature_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", point_3d_feature_t._get_packed_fingerprint())[0]

