"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class clock_t(object):

    __slots__ = ["timestamp"]

    __typenames__ = ["float"]

    __dimensions__ = [None]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(clock_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.timestamp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != clock_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return clock_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = clock_t()
        self.timestamp = struct.unpack(">f", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if clock_t in parents: return 0
        tmphash = (0xa727be7fb5e0e800) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if clock_t._packed_fingerprint is None:
            clock_t._packed_fingerprint = struct.pack(">Q", clock_t._get_hash_recursive([]))
        return clock_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", clock_t._get_packed_fingerprint())[0]

