"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
lcm-gen 1.5.1
"""

from .camera_info_t import camera_info_t as camera_info_t
from .rgbd_t import rgbd_t as rgbd_t
