"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class vec_list_t(object):

    __slots__ = ["timestamp", "num_vecs", "vec_dim", "name_list", "vec_list"]

    __typenames__ = ["double", "int32_t", "int32_t", "string", "float"]

    __dimensions__ = [None, None, None, ["num_vecs"], ["num_vecs", "vec_dim"]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.num_vecs = 0
        """ LCM Type: int32_t """
        self.vec_dim = 0
        """ LCM Type: int32_t """
        self.name_list = []
        """ LCM Type: string[num_vecs] """
        self.vec_list = []
        """ LCM Type: float[num_vecs][vec_dim] """

    def encode(self):
        buf = BytesIO()
        buf.write(vec_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dii", self.timestamp, self.num_vecs, self.vec_dim))
        for i0 in range(self.num_vecs):
            __name_list_encoded = self.name_list[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__name_list_encoded)+1))
            buf.write(__name_list_encoded)
            buf.write(b"\0")
        for i0 in range(self.num_vecs):
            buf.write(struct.pack('>%df' % self.vec_dim, *self.vec_list[i0][:self.vec_dim]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vec_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vec_list_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = vec_list_t()
        self.timestamp, self.num_vecs, self.vec_dim = struct.unpack(">dii", buf.read(16))
        self.name_list = []
        for i0 in range(self.num_vecs):
            __name_list_len = struct.unpack('>I', buf.read(4))[0]
            self.name_list.append(buf.read(__name_list_len)[:-1].decode('utf-8', 'replace'))
        self.vec_list = []
        for i0 in range(self.num_vecs):
            self.vec_list.append(struct.unpack('>%df' % self.vec_dim, buf.read(self.vec_dim * 4)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if vec_list_t in parents: return 0
        tmphash = (0x8d0d22c73945e9e0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if vec_list_t._packed_fingerprint is None:
            vec_list_t._packed_fingerprint = struct.pack(">Q", vec_list_t._get_hash_recursive([]))
        return vec_list_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vec_list_t._get_packed_fingerprint())[0]

