"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class se3_pose_t(object):

    __slots__ = ["timestamp", "position", "quat_wxyz"]

    __typenames__ = ["double", "float", "float"]

    __dimensions__ = [None, [3], [4]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.quat_wxyz = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """

    def encode(self):
        buf = BytesIO()
        buf.write(se3_pose_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.timestamp))
        buf.write(struct.pack('>3f', *self.position[:3]))
        buf.write(struct.pack('>4f', *self.quat_wxyz[:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != se3_pose_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return se3_pose_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = se3_pose_t()
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        self.position = struct.unpack('>3f', buf.read(12))
        self.quat_wxyz = struct.unpack('>4f', buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if se3_pose_t in parents: return 0
        tmphash = (0xecf7ff2a39b39f78) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if se3_pose_t._packed_fingerprint is None:
            se3_pose_t._packed_fingerprint = struct.pack(">Q", se3_pose_t._get_hash_recursive([]))
        return se3_pose_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", se3_pose_t._get_packed_fingerprint())[0]

