"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class joint_ctrl_t(object):

    __slots__ = ["timestamp", "num_joints", "q_des", "qd_des", "tau_ff", "kp", "kd", "valid"]

    __typenames__ = ["double", "int32_t", "float", "float", "float", "float", "float", "boolean"]

    __dimensions__ = [None, None, ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], None]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.q_des = []
        """ LCM Type: float[num_joints] """
        self.qd_des = []
        """ LCM Type: float[num_joints] """
        self.tau_ff = []
        """ LCM Type: float[num_joints] """
        self.kp = []
        """ LCM Type: float[num_joints] """
        self.kd = []
        """ LCM Type: float[num_joints] """
        self.valid = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(joint_ctrl_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">di", self.timestamp, self.num_joints))
        buf.write(struct.pack('>%df' % self.num_joints, *self.q_des[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.qd_des[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.tau_ff[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.kp[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.kd[:self.num_joints]))
        buf.write(struct.pack(">b", self.valid))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_ctrl_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_ctrl_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = joint_ctrl_t()
        self.timestamp, self.num_joints = struct.unpack(">di", buf.read(12))
        self.q_des = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.qd_des = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.tau_ff = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.kp = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.kd = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.valid = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if joint_ctrl_t in parents: return 0
        tmphash = (0xa32cb1e10d48f17e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if joint_ctrl_t._packed_fingerprint is None:
            joint_ctrl_t._packed_fingerprint = struct.pack(">Q", joint_ctrl_t._get_hash_recursive([]))
        return joint_ctrl_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", joint_ctrl_t._get_packed_fingerprint())[0]

