"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class joint_meas_t(object):

    __slots__ = ["timestamp", "num_joints", "q", "qd", "tau"]

    __typenames__ = ["double", "int32_t", "float", "float", "float"]

    __dimensions__ = [None, None, ["num_joints"], ["num_joints"], ["num_joints"]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.q = []
        """ LCM Type: float[num_joints] """
        self.qd = []
        """ LCM Type: float[num_joints] """
        self.tau = []
        """ LCM Type: float[num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(joint_meas_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">di", self.timestamp, self.num_joints))
        buf.write(struct.pack('>%df' % self.num_joints, *self.q[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.qd[:self.num_joints]))
        buf.write(struct.pack('>%df' % self.num_joints, *self.tau[:self.num_joints]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_meas_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_meas_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = joint_meas_t()
        self.timestamp, self.num_joints = struct.unpack(">di", buf.read(12))
        self.q = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.qd = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        self.tau = struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if joint_meas_t in parents: return 0
        tmphash = (0xe2c832643d5e41e7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if joint_meas_t._packed_fingerprint is None:
            joint_meas_t._packed_fingerprint = struct.pack(">Q", joint_meas_t._get_hash_recursive([]))
        return joint_meas_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", joint_meas_t._get_packed_fingerprint())[0]

