"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class joint_traj_t(object):

    __slots__ = ["timestamp", "num_joints", "num_points", "t", "q", "qd"]

    __typenames__ = ["double", "int32_t", "int32_t", "float", "float", "float"]

    __dimensions__ = [None, None, None, ["num_points"], ["num_points", "num_joints"], ["num_points", "num_joints"]]

    def __init__(self):
        self.timestamp = 0.0
        """ LCM Type: double """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.num_points = 0
        """ LCM Type: int32_t """
        self.t = []
        """ LCM Type: float[num_points] """
        self.q = []
        """ LCM Type: float[num_points][num_joints] """
        self.qd = []
        """ LCM Type: float[num_points][num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(joint_traj_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dii", self.timestamp, self.num_joints, self.num_points))
        buf.write(struct.pack('>%df' % self.num_points, *self.t[:self.num_points]))
        for i0 in range(self.num_points):
            buf.write(struct.pack('>%df' % self.num_joints, *self.q[i0][:self.num_joints]))
        for i0 in range(self.num_points):
            buf.write(struct.pack('>%df' % self.num_joints, *self.qd[i0][:self.num_joints]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_traj_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_traj_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = joint_traj_t()
        self.timestamp, self.num_joints, self.num_points = struct.unpack(">dii", buf.read(16))
        self.t = struct.unpack('>%df' % self.num_points, buf.read(self.num_points * 4))
        self.q = []
        for i0 in range(self.num_points):
            self.q.append(struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4)))
        self.qd = []
        for i0 in range(self.num_points):
            self.qd.append(struct.unpack('>%df' % self.num_joints, buf.read(self.num_joints * 4)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if joint_traj_t in parents: return 0
        tmphash = (0x23e300a80b1793cc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if joint_traj_t._packed_fingerprint is None:
            joint_traj_t._packed_fingerprint = struct.pack(">Q", joint_traj_t._get_hash_recursive([]))
        return joint_traj_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", joint_traj_t._get_packed_fingerprint())[0]

